
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 13 00:28:10 CET 2009
//----------------------------------------------------

package hr.fer.ppj.lab;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L_POSMAK = 29;
  public static final int LJESTVE = 2;
  public static final int CHAR = 51;
  public static final int AND_AND = 25;
  public static final int ZAREZ = 4;
  public static final int PLUS_JEDNAKO = 19;
  public static final int MINUS_MINUS = 16;
  public static final int PUTA_JEDNAKO = 21;
  public static final int CASE = 39;
  public static final int DOUBLE = 49;
  public static final int MINUS_JEDNAKO = 20;
  public static final int CONTINUE = 41;
  public static final int INT = 48;
  public static final int FOR = 54;
  public static final int MINUS = 14;
  public static final int Ident = 57;
  public static final int DIJELJENO_JEDNAKO = 22;
  public static final int Const_FLOAT = 59;
  public static final int RAZLICITO = 37;
  public static final int TILDA = 31;
  public static final int AND = 24;
  public static final int Const_INT = 58;
  public static final int OKOMITA = 26;
  public static final int JEDNAKO = 32;
  public static final int D_POSMAK = 30;
  public static final int L_UGLATA_ZAGRADA = 9;
  public static final int L_VITICASTA_ZAGRADA = 11;
  public static final int PLUS = 13;
  public static final int MAIN = 46;
  public static final int IF = 43;
  public static final int KAPA = 28;
  public static final int EOF = 0;
  public static final int RETURN = 55;
  public static final int PLUS_PLUS = 15;
  public static final int TOCKA = 3;
  public static final int L_OBICNA_ZAGRADA = 7;
  public static final int error = 1;
  public static final int INCLUDE = 47;
  public static final int VECE_JEDNAKO = 35;
  public static final int MOD = 23;
  public static final int BREAK = 53;
  public static final int MANJE_JEDNAKO = 36;
  public static final int VOID = 56;
  public static final int SWITCH = 38;
  public static final int OKOMITA_OKOMITA = 27;
  public static final int D_UGLATA_ZAGRADA = 10;
  public static final int MANJE = 34;
  public static final int ELSE = 44;
  public static final int VECE = 33;
  public static final int String = 60;
  public static final int WHILE = 52;
  public static final int DIJELJENO = 18;
  public static final int DEFAULT = 40;
  public static final int FLOAT = 50;
  public static final int TOCKA_ZAREZ = 6;
  public static final int D_VITICASTA_ZAGRADA = 12;
  public static final int DVOTOCKA = 5;
  public static final int D_OBICNA_ZAGRADA = 8;
  public static final int PUTA = 17;
  public static final int STRUCT = 42;
  public static final int DO = 45;
}
