
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 17 15:55:13 CET 2010
//----------------------------------------------------

package hr.fer.ppj.lab;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 18;
  public static final int ZAREZ = 30;
  public static final int TOCKAZAREZ = 32;
  public static final int GREATER = 12;
  public static final int CONTINUE = 29;
  public static final int INT = 17;
  public static final int LESS = 11;
  public static final int FOR = 27;
  public static final int MINUS = 3;
  public static final int NOT = 16;
  public static final int AND = 7;
  public static final int CONST_CHAR = 43;
  public static final int OR = 8;
  public static final int VITICASTA_L = 38;
  public static final int DIV = 5;
  public static final int GEQ = 14;
  public static final int UGLATA_L = 36;
  public static final int CONST_FLOAT = 42;
  public static final int PLUS = 2;
  public static final int IF = 23;
  public static final int VITICASTA_D = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 39;
  public static final int UGLATA_D = 35;
  public static final int EQUAL = 10;
  public static final int TOCKA = 31;
  public static final int IDN = 40;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int OBLA_L = 34;
  public static final int MOD = 6;
  public static final int BREAK = 28;
  public static final int VOID = 22;
  public static final int ASSINGMENT = 9;
  public static final int OBLA_D = 33;
  public static final int ELSE = 24;
  public static final int WHILE = 26;
  public static final int FLOAT = 19;
  public static final int LEQ = 13;
  public static final int CONST_STR = 44;
  public static final int STRUCT = 21;
  public static final int DO = 25;
  public static final int CONST_INT = 41;
  public static final int NOTEQ = 15;
}

